# Generated by Django 2.1.2 on 2019-03-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yskauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(default='中医副主任医师', max_length=50),
        ),
    ]
